# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190119_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('isAC', models.BooleanField()),
                ('transmission', models.BooleanField()),
                ('color', models.CharField(max_length=20)),
                ('miles', models.CharField(max_length=20)),
                ('totalAmount', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('grandTotal', models.IntegerField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_modified', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invoice')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Part')),
            ],
        ),
    ]
