# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customer_invoice_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='motor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='isAC',
            field=models.BooleanField(choices=[(True, 'AC'), (False, 'Without AC')], default='AC'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='miles',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='model',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transmission',
            field=models.BooleanField(choices=[(True, 'Automatic'), (False, 'Manual')], default='Automatic'),
        ),
    ]
