# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190119_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grandTotal',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalAmount',
            field=models.IntegerField(blank=True),
        ),
    ]
