# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190120_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitems',
            old_name='itemID',
            new_name='partID',
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='part_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
