# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190121_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Part'),
        ),
    ]
