# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 18:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190121_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grandTotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalAmount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Part'),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
