# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190123_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(null=True),
        ),
    ]
