# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 16:58
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190123_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoiceNo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='invoiceitems',
            name='itemType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='itemType',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='isAC',
            field=models.BooleanField(choices=[(True, 'AC'), (False, 'No AC')], default='AC'),
        ),
    ]
