# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 10:42
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20190129_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='part',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
