# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 10:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190131_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
