# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20190202_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='labourTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='partTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='taxAmount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
