# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-09 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190208_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='taxAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
