# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20190209_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='taxAmount',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='totalAmount',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
