# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-17 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20190217_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grandTotal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='labourTotal',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='partTotal',
            field=models.BigIntegerField(),
        ),
    ]
